version: '3'
services:
  bluefoot:
    image: ${IMAGE_NAME}:latest
    deploy:
      replicas: 1
      labels:
        xyz.tangerie.reverse_proxy.path: "/"
        xyz.tangerie.reverse_proxy.port: "80"
        xyz.tangerie.reverse_proxy.server_name: "${SERVER_PREFIX}.tangerie.xyz"
    networks:
      - nginx-proxy-overlay

networks:
  nginx-proxy-overlay:
    external: true
    driver: overlay