name: Development Build

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      image_name: bluefootdev
      registry_name: docker.tangerie.xyz
      ref: dev
    secrets: inherit
    
  deploy:
    uses: ./.github/workflows/docker-deploy.yml
    needs: build
    with:
      image_name: bluefootdev
      registry_name: docker.tangerie.xyz
      compose_file_path: docker-compose-dev.yml
    secrets: inherit